// Paquets russes préchargés.
// Chaque carte : q = question (recto), a = réponse (verso),
// p = phonétique française, audio (optionnel) = texte russe à prononcer
// (par défaut, on prononce la réponse).

export const DECKS = [
  {
    id: 'alphabet',
    name: 'Alphabet cyrillique',
    // Pour l'alphabet, la question est la lettre russe (lue en audio),
    // la réponse est la translittération + le repère phonétique.
    cards: [
      { q: 'А а', a: 'a', p: 'comme « a » dans papa', audio: 'А' },
      { q: 'Б б', a: 'b', p: 'comme « b » dans bateau', audio: 'Б' },
      { q: 'В в', a: 'v', p: 'comme « v » dans valise', audio: 'В' },
      { q: 'Г г', a: 'g', p: 'comme « g » dans gare', audio: 'Г' },
      { q: 'Д д', a: 'd', p: 'comme « d » dans douche', audio: 'Д' },
      { q: 'Е е', a: 'ié / yé', p: 'comme « ié » dans pied', audio: 'Е' },
      { q: 'Ё ё', a: 'io / yo', p: 'comme « io » dans yoyo', audio: 'Ё' },
      { q: 'Ж ж', a: 'j', p: 'comme « j » dans journal', audio: 'Ж' },
      { q: 'З з', a: 'z', p: 'comme « z » dans zéro', audio: 'З' },
      { q: 'И и', a: 'i', p: 'comme « i » dans ami', audio: 'И' },
      { q: 'Й й', a: 'y', p: 'i bref, comme « y » dans yoga', audio: 'Й' },
      { q: 'К к', a: 'k', p: 'comme « k » dans kilo', audio: 'К' },
      { q: 'Л л', a: 'l', p: 'comme « l » dans lune', audio: 'Л' },
      { q: 'М м', a: 'm', p: 'comme « m » dans maman', audio: 'М' },
      { q: 'Н н', a: 'n', p: 'comme « n » dans nuit', audio: 'Н' },
      { q: 'О о', a: 'o', p: 'comme « o » dans porte', audio: 'О' },
      { q: 'П п', a: 'p', p: 'comme « p » dans papa', audio: 'П' },
      { q: 'Р р', a: 'r', p: 'r roulé (espagnol/italien)', audio: 'Р' },
      { q: 'С с', a: 's', p: 'comme « s » dans soleil', audio: 'С' },
      { q: 'Т т', a: 't', p: 'comme « t » dans table', audio: 'Т' },
      { q: 'У у', a: 'ou', p: 'comme « ou » dans cou', audio: 'У' },
      { q: 'Ф ф', a: 'f', p: 'comme « f » dans face', audio: 'Ф' },
      { q: 'Х х', a: 'kh', p: 'comme la « jota » espagnole', audio: 'Х' },
      { q: 'Ц ц', a: 'ts', p: 'comme « ts » dans tsar', audio: 'Ц' },
      { q: 'Ч ч', a: 'tch', p: 'comme « tch » dans tchèque', audio: 'Ч' },
      { q: 'Ш ш', a: 'ch', p: 'comme « ch » dans chat', audio: 'Ш' },
      { q: 'Щ щ', a: 'chtch', p: 'comme « ch » mouillé et long', audio: 'Щ' },
      { q: 'Ъ ъ', a: 'signe dur', p: 'muet, durcit la consonne', audio: 'твёрдый знак' },
      { q: 'Ы ы', a: 'y', p: 'i guttural, en arrière', audio: 'Ы' },
      { q: 'Ь ь', a: 'signe mou', p: 'muet, mouille la consonne', audio: 'мягкий знак' },
      { q: 'Э э', a: 'è', p: 'comme « è » dans père', audio: 'Э' },
      { q: 'Ю ю', a: 'iou / you', p: 'comme « iou » dans caillou', audio: 'Ю' },
      { q: 'Я я', a: 'ia / ya', p: 'comme « ia » dans piano', audio: 'Я' },
    ],
  },
  {
    id: 'politesse',
    name: 'Formules de politesse',
    cards: [
      { q: 'Bonjour (formel)', a: 'Здравствуйте', p: 'zdrastvouïtié' },
      { q: 'Salut', a: 'Привет', p: 'priviét' },
      { q: 'Bonsoir', a: 'Добрый вечер', p: 'dobryï viétchèr' },
      { q: 'Bonne nuit', a: 'Спокойной ночи', p: 'spakoïnoï notchi' },
      { q: 'Au revoir', a: 'До свидания', p: 'da svidania' },
      { q: 'Merci', a: 'Спасибо', p: 'spassiba' },
      { q: 'Merci beaucoup', a: 'Большое спасибо', p: 'balchoïe spassiba' },
      { q: 'S’il vous plaît / Je vous en prie', a: 'Пожалуйста', p: 'pajalousta' },
      { q: 'Oui', a: 'Да', p: 'da' },
      { q: 'Non', a: 'Нет', p: 'niét' },
      { q: 'Excusez-moi / Pardon', a: 'Извините', p: 'izvinitié' },
      { q: 'Comment allez-vous ?', a: 'Как дела?', p: 'kak diéla' },
      { q: 'Bien, merci', a: 'Хорошо, спасибо', p: 'kharacho spassiba' },
      { q: 'Comment vous appelez-vous ?', a: 'Как вас зовут?', p: 'kak vas zavout' },
      { q: 'Je m’appelle…', a: 'Меня зовут…', p: 'minia zavout' },
      { q: 'Enchanté', a: 'Очень приятно', p: 'otchin priïatna' },
      { q: 'De rien', a: 'Не за что', p: 'nié za chto' },
      { q: 'Bienvenue', a: 'Добро пожаловать', p: 'dabro pajalavat' },
      { q: 'Je ne comprends pas', a: 'Я не понимаю', p: 'ia nié panimaïou' },
      { q: 'Parlez-vous français ?', a: 'Вы говорите по-французски?', p: 'vy gavaritié pa-frantsouski' },
    ],
  },
  {
    id: 'jours',
    name: 'Jours de la semaine',
    cards: [
      { q: 'Lundi', a: 'Понедельник', p: 'panidiélnik' },
      { q: 'Mardi', a: 'Вторник', p: 'ftornik' },
      { q: 'Mercredi', a: 'Среда', p: 'srida' },
      { q: 'Jeudi', a: 'Четверг', p: 'tchitviérk' },
      { q: 'Vendredi', a: 'Пятница', p: 'piatnitsa' },
      { q: 'Samedi', a: 'Суббота', p: 'soubota' },
      { q: 'Dimanche', a: 'Воскресенье', p: 'vaskrissénié' },
    ],
  },
  {
    id: 'mois',
    name: 'Mois de l’année',
    cards: [
      { q: 'Janvier', a: 'Январь', p: 'yanvar' },
      { q: 'Février', a: 'Февраль', p: 'fivral' },
      { q: 'Mars', a: 'Март', p: 'mart' },
      { q: 'Avril', a: 'Апрель', p: 'apriél' },
      { q: 'Mai', a: 'Май', p: 'maï' },
      { q: 'Juin', a: 'Июнь', p: 'iyoun' },
      { q: 'Juillet', a: 'Июль', p: 'iyoul' },
      { q: 'Août', a: 'Август', p: 'avgoust' },
      { q: 'Septembre', a: 'Сентябрь', p: 'sintiabr' },
      { q: 'Octobre', a: 'Октябрь', p: 'aktiabr' },
      { q: 'Novembre', a: 'Ноябрь', p: 'naïabr' },
      { q: 'Décembre', a: 'Декабрь', p: 'dikabr' },
    ],
  },
  {
    id: 'chiffres',
    name: 'Chiffres 0-20',
    cards: [
      { q: '0', a: 'Ноль', p: 'nol' },
      { q: '1', a: 'Один', p: 'adin' },
      { q: '2', a: 'Два', p: 'dva' },
      { q: '3', a: 'Три', p: 'tri' },
      { q: '4', a: 'Четыре', p: 'tchityri' },
      { q: '5', a: 'Пять', p: 'piat' },
      { q: '6', a: 'Шесть', p: 'chest' },
      { q: '7', a: 'Семь', p: 'siém' },
      { q: '8', a: 'Восемь', p: 'vossiém' },
      { q: '9', a: 'Девять', p: 'diéviat' },
      { q: '10', a: 'Десять', p: 'diéssiat' },
      { q: '11', a: 'Одиннадцать', p: 'adinatsat' },
      { q: '12', a: 'Двенадцать', p: 'dvinatsat' },
      { q: '13', a: 'Тринадцать', p: 'trinatsat' },
      { q: '14', a: 'Четырнадцать', p: 'tchityrnatsat' },
      { q: '15', a: 'Пятнадцать', p: 'piatnatsat' },
      { q: '16', a: 'Шестнадцать', p: 'chesnatsat' },
      { q: '17', a: 'Семнадцать', p: 'simnatsat' },
      { q: '18', a: 'Восемнадцать', p: 'vassimnatsat' },
      { q: '19', a: 'Девятнадцать', p: 'diviatnatsat' },
      { q: '20', a: 'Двадцать', p: 'dvatsat' },
    ],
  },
  {
    id: 'dizaines',
    name: 'Dizaines 30-100',
    cards: [
      { q: '30', a: 'Тридцать', p: 'tritsat' },
      { q: '40', a: 'Сорок', p: 'sorak' },
      { q: '50', a: 'Пятьдесят', p: 'piatdissiat' },
      { q: '60', a: 'Шестьдесят', p: 'chesdissiat' },
      { q: '70', a: 'Семьдесят', p: 'siémdissiat' },
      { q: '80', a: 'Восемьдесят', p: 'vossimdissiat' },
      { q: '90', a: 'Девяносто', p: 'divianosta' },
      { q: '100', a: 'Сто', p: 'sto' },
    ],
  },
];

// Configuration des 5 boîtes de Leitner.
// intervalDays = délai avant la prochaine révision après une bonne réponse.
export const BOXES = [
  { box: 1, label: 'chaque jour', intervalDays: 1, color: '#E63946' },
  { box: 2, label: 'tous les 3 jours', intervalDays: 3, color: '#E76F51' },
  { box: 3, label: 'chaque semaine', intervalDays: 7, color: '#F4A261' },
  { box: 4, label: 'tous les 15 jours', intervalDays: 15, color: '#2A9D8F' },
  { box: 5, label: 'chaque mois', intervalDays: 30, color: '#264653' },
];

export const boxConfig = (box) => BOXES[Math.min(Math.max(box, 1), 5) - 1];
